### ISSUE TITLE
Updated Embed.php to use correct DocTypes

### ISSUE THREAD

**Issue by StevenWillett** [cyberhorse/metabase-php#1]
I have forked and updated the Embed.php file to use correct DocTypes and includes use case that was also missing.

Tried to create pull request, but not able, possibly disabled :)

See fork here: https://github.com/StevenWillett/metabase-php

Hope this helps others.

**Comment by ipeevski** [comment]
Hey Steven, thanks for your contribution. 
Let's try to figure out how to do the pull request so it keeps your attribution. I haven't disabled anything and can't seem to find an option about it. How did you try to do it?

**Comment by ipeevski** [comment]
I figured it out. Pull requested and merged :)
