### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by spinaldf** [cyberhorse/metabase-php#3]
How can i add option of user and passwd?

I create index.php:

<?php
include 'vendor/autoload.php';

// The url of the metabase installation
$metabaseUrl = 'http://localhost:3000';
// The secret embed key from the admin settings screen
$metabaseKey = 'db9a8cac9c5d3abe3b79dc46f0d479fc85295204705278amd939sm38u3';
// The id of the dashboard (from the url)
$dashboardId = 1;
// Any parameters to pass to the dashboard
//$params = 'date' => '';

$metabase = new \Metabase\Embed($metabaseUrl, $metabaseKey);
// Generate the HTML to create an iframe with the embedded dashboard
//echo $metabase->dashboardIframe($dashboardId, $params);
echo $metabase->dashboardIframe($dashboardId);

?>

**Comment by ipeevski** [comment]
You can't (and shouldn't) use user/password. Generate API key through metabase's admin panel and use that as the $metabaseKey

Here is a link to the instructions of how to generate the key: https://github.com/metabase/metabase/blob/master/docs/administration-guide/13-embedding.md#enabling-embedding
